sudo: required
language: generic

services:
  - docker


before_install:
  - docker build -t dockerfront-aws -f Dockerfile .

script:
  - docker run -e CI=true dockerfront-aws npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'dockerfront'
  env: 'Dockerfront-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-448774642000'
  bucket_path: 'dockerfront'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY